// Generated by https://quicktype.io

export interface IProducto {
    isbn:             string;
    title:            string;
    pageCount:        number;
    precio:           string;
    publishedDate:    string;
    thumbnailUrl:     string;
    shortDescription: string;
    longDescription:  string;
    status:           string;
}

export interface IColumn {
    key: string;
    label: string;
}

const ColumLibro:IColumn[] = [
    {
        key: "isbn",
        label: "ISBN",
      },
      {
        key: "title",
        label: "TITLE",
      },
      {
        key: "page",
        label: "PAGE",
      },
      {
        key: "precio",
        label: "PRECIO",
      },
      {
        key: "thumbnailUrl",
        label: "Imagen",
      },
]
export default ColumLibro